accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from accounts.views import CustomPasswordResetConfirmView, CustomPasswordResetView

from .views import *

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("signup", signup_view, name="signup"),
    path(
        "activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
        activate,
        name="activate",
    ),
    path(
        "password_reset/",
        CustomPasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            success_url=reverse_lazy("accounts:login"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path

from accounts.views import maintenance
from blogApp.sitemaps import BlogSitemap
from projectApp.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projectApp.urls")),
    path("accounts/", include("accounts.urls")),
    path("blogApp/", include("blogApp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    # ! for the MAINTANANCE_MODE
    path("maintenance/", maintenance, name="maintenance"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler400 = "blogApp.views.error_400"
handler404 = "blogApp.views.error_404"
handler403 = "blogApp.views.error_403"
handler500 = "blogApp.views.error_500"

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

accounts/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class RegisterForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        )


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Email / Username")

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from accounts.forms import RegisterForm
from accounts.models import CustomUser
from accounts.tokens import account_activation_token


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    if "next" in request.POST:
                        messages.success(request, "You logged in successfully! 😀")
                        return redirect(request.POST.get("next"))
                    else:
                        messages.success(request, "You logged in successfully! 😀")
                        return redirect("/")
                else:
                    messages.error(
                        request, "Invalid username or password. Please try again! ❌"
                    )
            else:
                messages.error(
                    request,
                    "Invalid form submission. Please check the entered data! ❌",
                )
        else:
            form = AuthenticationForm()
        context = {"form": form}
        return render(request, "accounts/login.html", context)
    else:
        return redirect("/")


@login_required
def logout_view(request):
    logout(request)
    messages.success(
        request,
        "You logged out successfully! 🎉",
    )
    return redirect("/")


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.save(commit=False)
                user.is_active = False
                user.save()

                current_site = get_current_site(request)
                mail_subject = "Activation link has been sent to your email id"
                message = render_to_string(
                    "acc_active_email.html",
                    {
                        "user": user,
                        "domain": current_site.domain,
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "token": account_activation_token.make_token(user),
                    },
                )
                to_email = form.cleaned_data.get("email")
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                messages.warning(
                    request, "We have sent you an email; please confirm 📧"
                )
                return redirect("accounts:login")
            elif not form.is_valid():
                if "username" in form.errors:
                    messages.error(request, "Username already exists! ❌")
                if "email" in form.errors:
                    messages.error(request, "Email already exists! ❌")
                if "password1" in form.errors:
                    messages.error(request, "Password is too weak! ❌")
                if "password2" in form.errors:
                    messages.error(request, "Passwords are not match! ❌")
                if "captcha" in form.errors:
                    messages.error(request, "Invalid Captcha! Please try again! ❌")

        form = RegisterForm()
        context = {"form": form}
        return render(request, "accounts/signup.html", context)
    else:
        return redirect("/")


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        response = HttpResponse(
            "Thank you for your email confirmation. Now you can login to your account."
        )
        response["Refresh"] = f"3;url={reverse('accounts:login')}"
        return response
    else:
        return HttpResponse("Activation link is invalid!")


class CustomPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "accounts/password_reset_confirm.html"
    success_url = "/accounts/login/"

    def form_valid(self, form):
        uidb64 = self.kwargs["uidb64"]
        token = self.kwargs["token"]
        user = self.get_user(uidb64)

        new_password = form.cleaned_data["new_password1"]

        if user.check_password(new_password):
            messages.error(
                self.request, "New password cannot be the same as the old password! 🚫"
            )
            return self.form_invalid(form)

        user.set_password(new_password)
        user.save()

        messages.success(self.request, "Password reset successful! 🎉")
        return super().form_valid(form)


class CustomPasswordResetView(PasswordResetView):
    def form_valid(self, form):
        email = form.cleaned_data.get("email")

        if CustomUser.objects.filter(email=email).exists():
            messages.success(
                self.request,
                "Password reset email has been sent. Please check your inbox. 💌",
            )
        else:
            messages.error(self.request, "User with this email does not exist! 🚫")
            return redirect(reverse_lazy("accounts:password_reset"))

        return super().form_valid(form)


# ! for the MAINTANANCE_MODE
def maintenance(request):
    return render(request, "maintenance.html")

templates/accounts/login.html
{% extends "base.html" %} {% load static %} {% block content %}
<div style="height:100px">
    <section class="banner-area relative blog-home-banner"  id="home">
    </section>
</div>
<div class="limiter" id="scrollTarget">
    <div class="container-login100">
        <div class="wrap-login100 p-b-90">
            <form
                class="login100-form validate-form flex-sb flex-w"
                method="POST"
                action={% url 'accounts:login' %}
            >
                {% csrf_token %}
                <span class="login100-form-title p-b-51"> Login </span>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Username or email is required"
                >
                {% if request.GET.next %}
                <input
                type="hidden"
                name='next'
                value="{{ request.GET.next }}"
                />
                {% endif %}
                    <input
                        class="input100"
                        type="text"
                        name="username"
                        placeholder="Username or email"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="password"
                        name="password"
                        placeholder="Password"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div class="flex-sb-m w-full p-t-3 p-b-24">
                    <div class="contact100-form-checkbox w-full">
                        <div
                        class="contact100-form-checkbox d-flex justify-content-between w-full" >
                        <a style="text-align: left"
                            href="{% url 'accounts:signup' %}"
                        >not registered yet?</a>
                        <a style="text-align: right;"
                            href="{% url 'accounts:password_reset' %}"
                        >forgot password</a>
                        </div>
                    </div>
                </div>
                <div class="container-login100-form-btn m-t-17">
                    <button type='submit' class="login100-form-btn">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="dropDownSelect1"></div>
<script>
    window.onload = function () {
        // Select the element you want to scroll to
        const element = document.getElementById("scrollTarget");

        // Scroll to that element
        element.scrollIntoView({ behavior: "smooth" });
    };
</script>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="banner-area relative blog-home-banner" id="home"></section>
<div class="limiter" id="scrollTarget">
    <div class="container-login100">
        <div class="wrap-login100 p-b-220">
            <form
                style="position: relative"
                class="login100-form validate-form flex-sb flex-w"
                method="POST"
            >
                {% csrf_token %}
                <span class="login100-form-title p-b-51">New Password</span>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="password"
                        name="new_password1"
                        placeholder="Password"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="password"
                        name="new_password2"
                        placeholder="Confirm Password"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div class="container-login100-form-btn m-t-17">
                    <button type="submit" class="login100-form-btn">
                        Confirm
                    </button>
                </div>
            </form>
            {% comment %} <ul>
            {% for error in form.errors %}
                <li class="alert-danger">{{error}}</li>
            {% endfor %}
            <ul> {% endcomment %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}

            {% if form.errors %}
                <div class="alert alert-error">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                        <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                    {{ form.non_field_errors }}
                {% endif %}
                </div>
            {% endif %}
            <br />
        </div>
    </div>
</div>
<div id="dropDownSelect1"></div>
<script>
    window.onload = function () {
        // Select the element you want to scroll to
        const element = document.getElementById("scrollTarget");

        // Scroll to that element
        element.scrollIntoView({ behavior: "smooth" });
    };
</script>
{% endblock %}

templates/accounts/password_reset_email.html
{% comment %}
<!-- prettier-ignore -->
{% endcomment %}
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/accounts/password_reset_form.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="banner-area relative blog-home-banner" id="home"></section>
<div class="limiter" id="scrollTarget">
    <div class="container-login100">
        <div class="wrap-login100 p-b-220">
            <form
                id="passwordResetForm"
                style="position: relative"
                class="login100-form validate-form flex-sb flex-w"
                method="POST"
            >
                {% csrf_token %}
                <span class="login100-form-title p-b-51">Password Reset</span>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="email"
                        name="email"
                        placeholder="Enter your email"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div class="container-login100-form-btn m-t-17">
                    <button type="submit" class="login100-form-btn">
                        Send Reset Email
                    </button>
                </div>
            </form>
            <br />
        </div>
    </div>
</div>
<div id="dropDownSelect1"></div>
<script>
    window.onload = function () {
        // Select the element you want to scroll to
        const element = document.getElementById("scrollTarget");

        // Scroll to that element
        element.scrollIntoView({ behavior: "smooth" });
    };
</script>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %} {% load static %} {% block content %}
<section class="banner-area relative blog-home-banner" id="home">
</section>
<div class="limiter" id="scrollTarget">
    <div class="container-login100">
        <div class="wrap-login100 p-b-90">
            <form
                style='position:relative'
                class="login100-form validate-form flex-sb flex-w"
                method="POST"
                action={% url 'accounts:signup' %}
            >
                {% csrf_token %}
                <span class="login100-form-title p-b-51"> Sign up </span>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="First name is required"
                >
                    <input
                        class="input100"
                        type="text"
                        name="first_name"
                        placeholder="First name"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Last name is required"
                >
                    <input
                        class="input100"
                        type="text"
                        name="last_name"
                        placeholder="Last name"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Username is required"
                >
                    <input
                        class="input100"
                        type="text"
                        name="username"
                        placeholder="Username"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Email is required"
                >
                    <input
                        class="input100"
                        type="email"
                        name="email"
                        placeholder="email"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="password"
                        name="password1"
                        placeholder="Password"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div
                    class="wrap-input100 validate-input m-b-16"
                    data-validate="Password is required"
                >
                    <input
                        class="input100"
                        type="password"
                        name="password2"
                        placeholder="Confirm Password"
                    />
                    <span class="focus-input100"></span>
                </div>
                <div class="flex-sb-m w-full p-t-3 p-b-24">
                    <div class="contact100-form-checkbox">
                        <input
                            class="input-checkbox100"
                            id="ckb1"
                            type="checkbox"
                            name="remember-me"
                        />
                    </div>
                </div>
                <div class="container-login100-form-btn m-t-17">
                    
                    <div class="contact100-form-checkbox" style="display:flex; justify-content:space-between; height:33px; position:absolute; bottom: 95px; right: 70px; overflow:hidden">
                        <div
                            class="alert-msg" style="width:100% ;border:1px solid black; border-radius:2px; overflow:hidden"
                            name="remember-me"
                        >{{form.captcha}}</div>
                    </div>
                    <button type='submit' class="login100-form-btn">Sign Up</button>
                    <div class="contact100-form-checkbox" >
                        <a
                            href="{% url 'accounts:login' %}"
                        >already have an account?</a>
                    </div>
                </div>
            </form>
            <br/>
        </div>      
    </div>
</div>
<div id="dropDownSelect1"></div>
<script>
    window.onload = function () {
        // Select the element you want to scroll to
        const element = document.getElementById("scrollTarget");

        // Determine the scroll position
        const offset = 0.23 * window.innerHeight; // 20% of the viewport height

        // Scroll to that position
        window.scrollBy({
            top: offset,
            behavior: "smooth"
        });
    };
</script>

{% endblock %}