blogApp/urls.py
from django.urls import path

from blogApp.feeds import LatestEntriesFeed

from .views import *

app_name = "blog"

urlpatterns = [
    path("", blog_home_view, name="blog-home"),
    path("category/<str:cat_name>/", blog_home_view, name="blog-category"),
    path("tags/<str:tag_name>/", blog_home_view, name="blog-tags"),
    path("author/<str:author_username>/", blog_home_view, name="blog-author"),
    path("search/", blog_search_view, name="blog-search"),
    path("blog-single/<int:pid>/", blog_single_view, name="blog-single"),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path

from accounts.views import maintenance
from blogApp.sitemaps import BlogSitemap
from projectApp.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projectApp.urls")),
    path("accounts/", include("accounts.urls")),
    path("blogApp/", include("blogApp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    # ! for the MAINTANANCE_MODE
    path("maintenance/", maintenance, name="maintenance"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler400 = "blogApp.views.error_400"
handler404 = "blogApp.views.error_404"
handler403 = "blogApp.views.error_403"
handler500 = "blogApp.views.error_500"

projectApp/urls.py
from django.urls import path

from .views import *

app_name = "website"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact"),
    path("newsletter/", newsletter_view, name="newsletter"),
]

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a
        ><img
            class="img-fluid"
            src="{%  static 'img/blog/ads-banner.jpg' %}"
            alt=""
    /></a>
</div>

templates/blog/blog-home.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content blog-header-content col-lg-12">
                <h1 class="text-white">Search What You Need!</h1>
                <p class="text-white">Find What You Want...</p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a>
                            <div class="thumb">
                                <img
                                    class="content-image img-fluid d-block mx-auto"
                                    src="{%  static 'img/blog/cat-widget1.jpg' %}"
                                    alt=""
                                />
                            </div>
                            <div class="content-details">
                                <h4
                                    class="content-title mx-auto text-uppercase"
                                >
                                    Backend
                                </h4>
                                <span></span>
                                <ul>
                                    <li>
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='django' %}"
                                            >django</a
                                        >,
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='python' %}"
                                            >python</a
                                        >,
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='ai' %}"
                                            >ai</a
                                        >
                                    </li>
                                </ul>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a>
                            <div class="thumb">
                                <img
                                    class="content-image img-fluid d-block mx-auto"
                                    src="{%  static 'img/blog/cat-widget2.jpg' %}"
                                    alt=""
                                />
                            </div>
                            <div class="content-details">
                                <h4
                                    class="content-title mx-auto text-uppercase"
                                >
                                    Wordpress
                                </h4>
                                <span></span>
                                <ul>
                                    <li>
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='wordpress' %}"
                                            >wordpress</a
                                        >
                                    </li>
                                </ul>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="single-cat-widget">
                    <div class="content relative">
                        <div class="overlay overlay-bg"></div>
                        <a>
                            <div class="thumb">
                                <img
                                    class="content-image img-fluid d-block mx-auto"
                                    src="{%  static 'img/blog/cat-widget3.jpg' %}"
                                    alt=""
                                />
                            </div>
                            <div class="content-details">
                                <h4
                                    class="content-title mx-auto text-uppercase"
                                >
                                    Frontend
                                </h4>
                                <span></span>
                                <ul>
                                    <li>
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='css' %}"
                                            >css</a
                                        >,
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='html' %}"
                                            >html</a
                                        >,
                                        <a
                                            style="color: #fff"
                                            href="{% url 'blog:blog-tags' tag_name='javascript' %}"
                                            >javascript</a
                                        >
                                    </li>
                                </ul>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                {% for post in posts %}
                <div class="single-post row">
                    <div class="col-lg-3 col-md-3 meta-details">
                        <ul class="tags">
                            {% for cat in post.category.all %}
                            <li>
                                <a
                                    href="{% url 'blog:blog-category' cat_name=cat %}"
                                    >{{cat}}</a
                                >
                            </li>
                            {% if not forloop.last %}, {% endif %} {% endfor %}
                        </ul>
                        <div class="user-details row">
                            <p class="user-name col-lg-12 col-md-12 col-6">
                                <a
                                    href="{% url 'blog:blog-author' author_username=post.author.first_name %}"
                                    >{{post.author.get_full_name}}</a
                                >
                                <span class="lnr lnr-user"></span>
                            </p>
                            <p class="date col-lg-12 col-md-12 col-6">
                                <a>{{post.published_date|date:"Y M D"}}</a>
                                <span class="lnr lnr-calendar-full"></span>
                            </p>
                            <p class="view col-lg-12 col-md-12 col-6">
                                <a>{{post.counted_views}} Views</a>
                                <span class="lnr lnr-eye"></span>
                            </p>
                            <p class="comments col-lg-12 col-md-12 col-6">
                                <a>{{comments|length}} Comments</a>
                                <span class="lnr lnr-bubble"></span>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9">
                        <div class="feature-img">
                            <img
                                class="img-fluid"
                                src="{{post.image.url}}"
                                alt=""
                            />
                        </div>
                        <a
                            class="posts-title"
                            href="{% url 'blog:blog-single' pid=post.id %}"
                        >
                            <h3>{{post.title}}</h3></a
                        >
                        <p class="excerpt">
                            {{ post.content|truncatewords:30 |safe }}
                        </p>
                        <a
                            href="{% url 'blog:blog-single' pid=post.id %}"
                            class="primary-btn"
                            >View More</a
                        >
                    </div>
                </div>
                {% empty %}
                <div
                    style="
                        display: inline-flex;
                        justify-content: center;
                        width: 100%;
                    "
                >
                    <h3>No Result :(</h3>
                </div>
                {% endfor %}
                <nav class="blog-pagination justify-content-center d-flex">
                    <ul class="pagination">
                        {% if posts.has_previous %}
                        <li class="page-item">
                            <a
                                href="?page={{posts.previous_page_number}}"
                                class="page-link"
                                aria-label="Previous"
                            >
                                <span aria-hidden="true">
                                    <span class="lnr lnr-chevron-left"></span>
                                </span>
                            </a>
                        </li>
                        {% endif %} {% for page in posts.paginator.page_range %}
                        {% if posts.number == page %}
                        <li class="page-item active" style="margin: 0 4px">
                            <a href="?page={{page}}" class="page-link"
                                >{{page}}</a
                            >
                        </li>
                        {% else %}
                        <li class="page-item" style="margin: 0 4px">
                            <a href="?page={{page}}" class="page-link"
                                >{{page}}</a
                            >
                        </li>
                        {% endif %} {% endfor %} {% if posts.has_next %}
                        <li class="page-item">
                            <a
                                href="?page={{posts.next_page_number}}"
                                class="page-link"
                                aria-label="Next"
                            >
                                <span aria-hidden="true">
                                    <span class="lnr lnr-chevron-right"></span>
                                </span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="col-lg-4 sidebar-widgets">
                {% include "./blog-sidebar.html" %}
            </div>
        </div>
    </div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %} {% load humanize %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img
                    style="width: 100px; height: 60px; overflow: hidden"
                    class="img-fluid"
                    src="{{post.image.url}}"
                    alt=""
                />
            </div>
            <div class="details">
                <a href="{% url 'blog:blog-single' pid=post.id %}"
                    ><h6>{{post.title}}</h6></a
                >
                <p>{{post.published_date|naturaltime}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-categories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Categories</h4>
    <ul class="cat-list">
        {% for name, count in categories.items|slice:":5" %}
        <li>
            <a
                href="{% url 'blog:blog-category' cat_name=name %}"
                class="d-flex justify-content-between"
            >
                <p>{{ name }}</p>
                <p>{{ count }}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-sidebar.html
{% load static %} {% load blog_tags %}

<div class="widget-wrap">
    <div class="single-sidebar-widget search-widget">
        <form
            class="search-form"
            action="{% url 'blog:blog-search' %}"
            method="GET"
        >
            <input
                placeholder="Search Posts"
                name="s"
                type="text"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Search Posts'"
            />
            <button type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>
    {% include "./blog-writer.html" %}
    <br />
    {% latest_post %} {% include "./blog-ads.html" %} {% post_category %}
</div>

templates/blog/blog-single.html
{% extends "base.html" %} {% load static %} {% load blog_tags %} {% block content %}
{% load humanize %}
<!-- start banner Area -->
<section class="relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">{{post.title}}</h1>
                <p class="text-white link-nav">
                    <a href={% url "website:index" %}>Home </a>
                    <span class="lnr lnr-arrow-right"></span
                    ><a href={% url "blog:blog-home" %}>Blog </a>
                    <span class="lnr lnr-arrow-right"></span>
                    {{current_post.title}}
                </p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post row">
                    <div class="col-lg-12">
                        <div class="feature-img">
                            <img
                                class="img-fluid"
                                src="{{current_post.image.url}}"
                                alt=""
                            />
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 meta-details">
                        <ul class="tags">
                            {% for cat in current_post.category.all %}
                            <li><a href="{% url 'blog:blog-category' cat_name=cat %}">{{cat}}</a></li>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </ul>
                        <div class="user-details row">
                            {% if author %}
                            <p class="user-name col-lg-12 col-md-12 col-6">
                                <a href="{% url 'blog:blog-author' author_username=author %}">{{author.get_full_name}}</a>
                                <span class="lnr lnr-user"></span>
                            </p>
                            {% endif %}
                            <p class="date col-lg-12 col-md-12 col-6">
                                <a
                                    >{{current_post.published_date|date:"d F Y"}}
                                </a>
                                <span class="lnr lnr-calendar-full"></span>
                            </p>
                            <p class="view col-lg-12 col-md-12 col-6">
                                <a>{{current_post.counted_views}} Views</a>
                                <span class="lnr lnr-eye"></span>
                            </p>
                            <p class="comments col-lg-12 col-md-12 col-6">
                                <a>{{comments|length}} Comments</a>
                                <span class="lnr lnr-bubble"></span>
                            </p>
                            <ul class="social-links col-lg-12 col-md-12 col-6">
                                <li>
                                    <a href="#"
                                        ><i class="fa fa-facebook"></i
                                    ></a>
                                </li>
                                <li>
                                    <a href="#"
                                        ><i class="fa fa-twitter"></i
                                    ></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-github"></i></a>
                                </li>
                                <li>
                                    <a href="#"
                                        ><i class="fa fa-behance"></i
                                    ></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9">
                        <h3 class="mt-20 mb-20">{{current_post.title}}</h3>
                        <p class="excert">{{current_post.content|safe}}</p>
                    </div>
                </div>
                <div class="navigation-area">
                    <div class="row" style="width: 760px; display: flex">
                        {% if prev_post %}
                        <div
                            class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center"
                        >
                            <div class="thumb">
                                <a href="{% url 'blog:blog-single' pid=prev_post.id %}"
                                    ><img
                                        style="width: 60px; height: 60px; overflow: hidden;"
                                        class="img-fluid"
                                        src="{{prev_post.image.url}}"
                                        alt=""
                                /></a>
                            </div>
                            <div class="arrow">
                                <a href="{% url 'blog:blog-single' pid=prev_post.id %}"
                                    ><span
                                        class="lnr text-white lnr-arrow-left"
                                    ></span
                                ></a>
                            </div>
                            <div class="detials">
                                <p>Prev Post</p>
                                <a href="{% url 'blog:blog-single' pid=prev_post.id %}"><h4>{{ prev_post.title }}</h4></a>
                            </div>
                        </div>
                        {% endif %}
                        {% if next_post %}
                        <div 
                            class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                            <div class="detials">
                                <p>Next Post</p>
                                <a href="{% url 'blog:blog-single' pid=next_post.id %}"><h4>{{ next_post.title }}</h4></a>
                            </div>
                            <div class="arrow">
                                <a href="{% url 'blog:blog-single' pid=next_post.id %}"
                                    ><span
                                        class="lnr text-white lnr-arrow-right"
                                    ></span
                                ></a>
                            </div>
                            <div class="thumb">
                                <a href="{% url 'blog:blog-single' pid=next_post.id %}"
                                    ><img
                                        style="width: 60px; height: 60px; overflow: hidden;"
                                        class="img-fluid"
                                        src="{{next_post.image.url}}"
                                        alt=""
                                /></a>
                            </div>
                        </div>
                        {% endif %}                    
                    </div>
                </div>
                <div class="comments-area">
                    <h4>{{comments|length}} Comments</h4>
                    <div class="comment-list">
                            {% for comment in comments %}
                            <div
                                class="single-comment justify-content-between d-flex mt-4">
                                <div class="user justify-content-between d-flex">
                                    <div class="thumb">
                                        <img
                                            style="width: 60px; height: 60px; overflow: hidden"
                                            src="{%  static 'img/blog/user-icon.jpg' %}"
                                            alt=""
                                        />
                                    </div>
                                    <div class="desc">
                                        <h5><a href="#">{{comment.name}}</a></h5>
                                        <p class="date">
                                            {{comment.created_date|naturalday}}
                                        </p>
                                        <p class="comment">
                                            {{comment.message}} 
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                        <p class="comment">
                            there is not any comments for this post yet
                        </p>
                    {% endfor %}
                        </div>
                    </div>
                <div class="comment-form">
                    <h4>Leave a Comment</h4>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <input type="hidden" name="post" value="{{current_post.id}}"/>
                        <div class="form-group form-inline">
                            <div class="form-group col-lg-6 col-md-12 name">
                                <input
                                    value="{{request.user.username}}"
                                    type="hidden"
                                    class="form-control"
                                    name="name"
                                    placeholder="Enter Name"
                                    onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter Name'"
                                />
                                <input
                                    disabled
                                    value="{{request.user.username}}"
                                    type="text"
                                    class="form-control"
                                    name="name"
                                    placeholder="Enter Name"
                                />
                            </div>
                            <div class="form-group col-lg-6 col-md-12 email">
                                <input
                                    value="{{request.user.email}}"
                                    type="hidden"
                                    class="form-control"
                                    name="email"
                                    placeholder="Enter email address"
                                    onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter email address'"
                                />
                                <input
                                    disabled
                                    value="{{request.user.email}}"
                                    type="email"
                                    class="form-control"
                                    name="email"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <input
                                type="text"
                                class="form-control"
                                name="subject"
                                placeholder="Subject"
                                onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Subject'"
                            />
                        </div>
                        <div class="form-group">
                            <textarea
                                class="form-control mb-10"
                                rows="5"
                                name="message"
                                placeholder="Messege"
                                onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Messege'"
                                required=""
                            ></textarea>
                        </div>
                        <button type="submit" class="primary-btn text-uppercase"
                            >Post Comment</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-4 sidebar-widgets">
                <div class="widget-wrap">
                    <div class="single-sidebar-widget tag-cloud-widget">
                        <h4 class="tagcloud-title">Post Tags</h4>
                        <ul>
                            {% for tag in current_post.tags.all %}
                            <li><a href="{% url 'blog:blog-tags' tag_name=tag.name %}">{{tag.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% include "./blog-sidebar.html" %}
            </div>
        </div>
    </div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img
        style="width: 120px; highet: 120px; overflow: hidden"
        src="{%  static 'img/blog/user-icon.jpg' %}"
        alt=""
    />
    <a><h4>Taregh Khaleghi</h4></a>
    <p>Junior Backend Developer</p>
    <ul class="social-links">
        <li>
            <a href="https://github.com/tareqWpy"
                ><i class="fa fa-github"></i
            ></a>
        </li>
    </ul>
</div>