accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from accounts.views import CustomPasswordResetConfirmView, CustomPasswordResetView

from .views import *

app_name = "accounts"

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("signup", signup_view, name="signup"),
    path(
        "activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/",
        activate,
        name="activate",
    ),
    path(
        "password_reset/",
        CustomPasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            success_url=reverse_lazy("accounts:login"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

blogApp/urls.py
from django.urls import path

from blogApp.feeds import LatestEntriesFeed

from .views import *

app_name = "blog"

urlpatterns = [
    path("", blog_home_view, name="blog-home"),
    path("category/<str:cat_name>/", blog_home_view, name="blog-category"),
    path("tags/<str:tag_name>/", blog_home_view, name="blog-tags"),
    path("author/<str:author_username>/", blog_home_view, name="blog-author"),
    path("search/", blog_search_view, name="blog-search"),
    path("blog-single/<int:pid>/", blog_single_view, name="blog-single"),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path

from accounts.views import maintenance
from blogApp.sitemaps import BlogSitemap
from projectApp.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projectApp.urls")),
    path("accounts/", include("accounts.urls")),
    path("blogApp/", include("blogApp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    # ! for the MAINTANANCE_MODE
    path("maintenance/", maintenance, name="maintenance"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler400 = "blogApp.views.error_400"
handler404 = "blogApp.views.error_404"
handler403 = "blogApp.views.error_403"
handler500 = "blogApp.views.error_500"

projectApp/urls.py
from django.urls import path

from .views import *

app_name = "website"

urlpatterns = [
    path("", home_view, name="index"),
    path("about/", about_view, name="about"),
    path("contact/", contact_view, name="contact"),
    path("newsletter/", newsletter_view, name="newsletter"),
]

templates/acc_active_email.html
{% comment %}
<!-- prettier-ignore -->
{% endcomment %}
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}  
{% endautoescape %}

templates/base.html
{% load static %} {% load compress %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta charset="UTF-8" />
    <meta name="robots" content="index, follow" />
    <meta property="og:title" content="blog for developers"/>
    <meta property="og:description" content="a great website for developers"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://djandotech.online"/>
    <title>DjangoTech</title>
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700"
      rel="stylesheet"
    />
    <!--
			CSS
			============================================= -->
    {% compress css %}
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" />
    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/bootstrap/css/bootstrap.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/animate/animate.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/css-hamburgers/hamburgers.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/animsition/css/animsition.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/select2/select2.min.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'vendor/daterangepicker/daterangepicker.css' %}"
    />

    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'css/util.css' %}"
    />
    <link
        rel="stylesheet"
        type="text/css"
        href="{%  static 'css/signin-login.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
    <style>
    
        #modal {
            position: fixed;
            top: 0;
            left: 0;
            width: 100vw;
            height: 100vh;
            background-color: rgba(225, 235, 255, 0.8);
            backdrop-filter: blur(10px);
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 9999;
            transition: opacity 0.5s; /* Smooth transition effect */
            opacity: 1; /* Initially visible */
             /* Enable interaction when visible */
            user-select:none;
        }

        /* Style for the content inside the modal */
        #modal-content {
            padding: 20px;
            background-color: #ebebebb3;
            border-radius: 10px;
        }
        /* HTML:  */
        .loader {
          width: 65px;
          height: 30px;
          position: relative;
        }
        .loader:before {
          content: "";
          position: absolute;
          border-radius: 50px;
          box-shadow: 0 0 0 3px inset #333;
          animation: l3 0.75s infinite alternate;
        }
        @keyframes l3 {
          0% {
            inset: 0 35px 0 0;
          }
          50% {
            inset: 0 0 0 0;
          }
          100% {
            inset: 0 0 0 35px;
          }
        }
        </style>
      {% endcompress %}
    </head>
    <body>
      <div id="modal">
        <div id="modal-content">
            <div class="loader"></div>
        </div>
    </div>
    <header id="header" >
      <div class="header-top">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 col-sm-6 col-6 header-top-left">
              <ul>
                {% if request.user.is_authenticated %}
                <li><a style="font-weight:400; color: #ffffff">Logged in as {{ user.username }}</a></li>
                <li><a href="{% url 'accounts:logout' %}" style="font-weight:400; color: #ffffff">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}" style="font-weight:400; color: #ffffff">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}" style="font-weight:400; color: #ffffff">Signup</a></li>
                {% endif %}
              </ul>
            </div>
            <div class="col-lg-6 col-sm-6 col-6 header-top-right">
              <div class="header-social">
                <a href="https://github.com/tareqWpy"
                    ><i class="fa fa-github"></i
                ></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href={% url "website:index" %}
              ><img src="{% static 'img/logo.png' %}" alt="" title=""
            /></a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li><a href={% url "website:index" %}>Home</a></li>
              <li><a href={% url "website:about" %} >About</a></li>
              <li>
                <a href={% url "blog:blog-home" %}>Blog</a>
                
              </li>
              <li>
              <li><a href={% url "website:contact" %}>Contact</a></li>
            </ul>
          </nav>
          <!-- #nav-menu-container -->
        </div>
      </div>
      {% if messages %}
        <ul id="popup-message" style="position: absolute; right: 20px;">
        {% for message in messages %}
          <li style="text-align:right" class="mt-3 alert{% if message.tags == 'error' %}
              alert-danger
            {% elif message.tags == 'success' %}
              alert-success
            {% elif message.tags == 'warning' %}
              alert-warning
            {% endif %}
            ">
            {{ message|safe }}
        </li>
        {% endfor %}
        <ul>
      {% endif %}
    </header>
    <!-- #header -->
    
    {% block content %}{% endblock %}
    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Agency</h6>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
              </p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Navigation Links</h6>
              <div class="row">
                <div class="col">
                  <ul>
                    <li><a href="{% url 'website:index'%}">Home</a></li>
                    <li><a href="{% url 'website:about'%}">About</a></li>
                  </ul>
                </div>
                <div class="col">
                  <ul>
                    <li><a href="{% url 'blog:blog-home'%}">Blog</a></li>
                    <li><a href="{% url 'website:contact'%}">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
              </p>
              <div>
                <form
                  action="{% url 'website:newsletter' %}"
                  method="POST"
                  class="subscription relative"
                >
                {% csrf_token %}
                  <div class="input-group d-flex flex-row">
                    <input
                      name="email"
                      placeholder="Email Address"
                      onfocus="this.placeholder = ''"
                      onblur="this.placeholder = 'Email Address '"
                      required=""
                      type="email"
                    />
                    <button type="submit" class="btn bb-btn">
                      <span class="lnr lnr-location"></span>
                    </button>
                    </div>
                    <div class="mt-10 info"></div>
                  <div >
                </div>
                    </form>
                    </div>
                </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">InstaFeed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li><a href="{% url 'blog:blog-tags' tag_name='django' %}"><img src="{% static 'img/i1.jpg' %}" alt="" /></a></li>
                <li><a href="{% url 'blog:blog-tags' tag_name='wordpress' %}"><img src="{% static 'img/i2.jpg' %}" alt="" /></a></li>
                <li><a href="{% url 'blog:blog-tags' tag_name='nuxt.js' %}"><img src="{% static 'img/i3.jpg' %}" alt="" /></a></li>
                <li><a href="{% url 'blog:blog-tags' tag_name='vue.js' %}"><img src="{% static 'img/i4.jpg' %}" alt="" /></a></li>
              </ul>
            </div>
          </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->
     <script>
        // Wait for the DOM to load
        document.addEventListener('DOMContentLoaded', function() {
            var modal = document.getElementById('modal');

            // Set a brief timeout to allow for a smooth transition
            setTimeout(function() {
                modal.style.opacity = '0';
                modal.style.pointerEvents = 'none'; // Disable interaction after transition
            }, 1000); // Adjust the timeout value to control transition duration

            // Enable pointer events on the modal to prevent interactions with elements behind it
            modal.style.pointerEvents = 'auto';
        });
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function () {
        const popupMessage = document.getElementById('popup-message');
        setTimeout(function () {
            popupMessage.style.display = 'none';
        }, 10000);
    });
    </script>
    `   {% compress js %}
        <script src="{%  static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>

        <script src="{%  static 'vendor/animsition/js/animsition.min.js' %}"></script>

        <script src="{%  static 'vendor/bootstrap/js/popper.js' %}"></script>
        <script src="{%  static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

        <script src="{%  static 'vendor/select2/select2.min.js' %}"></script>

        <script src="{%  static 'vendor/daterangepicker/moment.min.js' %}"></script>
        <script src="{%  static 'vendor/daterangepicker/daterangepicker.js' %}"></script>

        <script src="{%  static 'vendor/countdowntime/countdowntime.js' %}"></script>

        <script src="{%  static 'js/signin-login.js' %}"></script>

        
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag("js", new Date());

            gtag("config", "UA-23581568-13");
        </script>
    </script>
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endcompress %}
    <script
        async
        src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"
    ></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  </body>
</html>

templates/maintenance.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Site Maintenance</title>

        <style>
            body {
                text-align: center;
                padding: 250px 150px;
            }
            h1 {
                font-size: 50px;
                text-align: center;
            }
            body {
                font: 20px Helvetica, sans-serif;
                color: #333;
            }
            article {
                display: block;
                text-align: left;
                width: 100;
                max-width: 550px;
                margin: 0 auto;
            }
        </style>
    </head>
    <body>
        <article>
            <h1>به زودی در دسترس خواهد بود</h1>
            <div>
                <p>&mdash; DjangoTech Team</p>
            </div>
        </article>
    </body>
</html>